apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp3
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: myapplications/myapp3/
    repoURL: https://github.com/grcanosa/gitops.git
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
  # syncPolicy:
  #   automated:
  #     selfHeal: true
